name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

variables:
  - template: pipelines/vars.yml

trigger:
  branches:
    include:
      - master
      - feature/*

resources:
  - repo: self
    clean: all
    fetchDepth: 1

queue:
  name: Build
  demands:
    - npm


stages:
  - stage: Build
    jobs:
     - job: build
       steps:
         - template: pipeline/build.yml

  - stage: Artifact
    dependsOn: Build
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    jobs:
     - job: artifact
       steps:
         - template: pipeline/artifact.yml

  - stage: DeployDev
    dependsOn: Artifact
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    jobs:
     - deployment: deploy
       environment: pdn
       strategy:
        runOnce:
          deploy:
            steps:
            - template: pipeline/deploy.yml
              parameters:
                  extensionVisibility: private
                  shareWith: 
                  connectedServiceName: 
   
